import Head from 'next/head'
// import {Image as Img} from 'next/image'
// import dynamic from 'next/dynamic'
import { Heading, Flex, Stack, Text, Circle, useMediaQuery, Image, Box, useColorMode, FormControl,FormLabel,Switch, Grid, GridItem } from '@chakra-ui/react'
import Header from '../components/Header'
// import Sidebar from '../components/Sidebar'
import {
  React,
  useState,
  useEffect
} from 'react'
import Fonts from '../components/Fonts'

export default function Home() {
  const [tigaRatus50] = useMediaQuery('(max-width: 350px)')
  const [tigaRatus75] = useMediaQuery('(max-width: 375px)')
  const { colorMode, toggleColorMode } = useColorMode()

  const isDark = colorMode === 'dark'
  const opacity = isDark ? '.1' : '.2'

  // console.log(initial)

  const box = {
    filter: "auto",
    borderRadius: "md",
    position: "absolute",
    blur: "2px",
    zIndex: "-2",
    opacity: opacity
  }
  const bulet = {
    zIndex: "-1",
    filter: "auto",
    blur: "2px",
    position: 'absolute',
    opacity: opacity,
    display: ['none', 'none','block', 'block']
  }
  const boxAbout = {
    px: ['2','3','9','9'],
    pt: ['14','14','16','16'],
    pb: ['16','16','28','24'],
    mt: "32",
    position: "relative",
  }
  const textAbout = {
    fontSize: "xl",
    fontWeight: "light",
    mb: "2"
  }
  return (
    <>
      <Head>
        <title>Asep Dera Purnama | Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="project" content='Portofolio'></meta>
        <meta name="keyword" content='Portofolio, asep dera purnama, next.js, chakra-ui, js, javascript, react.js, css, back end developer'></meta>
        <link rel="icon" href="/favicon.ico" />
        <meta name='lang' content='indonesia'></meta>
      </Head>
      <Header/>
      <Fonts/>
      <Box bgGradient="linear(to-br,cyan.200,blue.400)" w="100px" right="20px" h="100px" top="40px" sx={box}> </Box>
      <Box bgGradient="linear(to-tr,teal.200,green.400)" w="100px" left="520px" h="100px" top="80px" sx={box}> </Box>
      <Box bgGradient="linear(to-tr,pink.200,cyan.300)" w="100px" h="200px" left="20px" top="70px" sx={box}> </Box>
      <Box bgGradient="linear(to-tr,red.200,orange.300)" w="100px" h="120px" left="350px" top="280px" sx={box}> </Box>
      <Box bgGradient="linear(to-bl,purple.400,pink.600)" w="400px" h="120px" left="250px" top="480px" sx={box}> </Box>
      <Stack as={"main"} py="36" id="home">
        {/* <Sidebar sx={data.tooltip ? data.tooltip : label} /> */}
        <Flex padding = "6"direction = {['column-reverse', 'column-reverse', 'row', 'row']}justify = "center"align = "center" >
          <Flex direction="column" w="50%" justif="center" align="center" py="8" textAlign="center" >
            <Heading size={tigaRatus75 ? "md" : "lg"}>Hai I am</Heading>
            <Heading size={tigaRatus75 ? "xl" : "2xl"} lineHeight={tigaRatus50 ? "8" : "normal"} my={tigaRatus75 ? "3" : ""}bgGradient={isDark ? "linear(to-br,cyan.400,blue.600)" : "linear(to-tr,pink.400,cyan.500)"}bgClip="text" > Asep Dera Purnama </Heading>
            <Heading my={tigaRatus75 ? "0" : "2"} as="h4" size={tigaRatus75 ? "md" : "lg"}>Back End Developer </Heading>
          </Flex>
          <Flex justify="center" align="center" w="50%" position="relative">
            <Circle right="160px" top="-15%" w={'150px'} h={'150px'} bgColor="blue.500" sx={bulet} />
            <Circle left="19%" bottom="21%" w={'200px'} h={'200px'} bgColor="red.500" sx={bulet} />
            <Circle right="34%" bottom="-15%" w={'120px'} h={'120px'} bgColor="green.500" sx={bulet} />
            <Box>
              <Image src='./poto.JPG' borderRadius="full" boxSize={[100,150,250,250]} boxShadow="dark-lg" alt="foto profile" />
            </Box>
          </Flex>
        </Flex>
      </Stack>
      <Box sx={boxAbout} id='about'>
        <Heading as="h3" align="center" pt="3" fontFamily="bogart" py=''> About Me </Heading>
        <Flex direction={['column', 'column', 'column', 'row']} align="center" justify="center">
          <Box w='30%' py='12' display={['none','none','none','flex']} alignItems="center" justifyContent="center">
            <Image src='./poto2.JPG' w='245px' h='450px' alt='foto about' boxShadow="lg" borderRadius='7px'></Image>
          </Box>
          <Flex direction="column" textAlign="justify" w={['100%','100%','100%',"70%"]} pb='28'>
            <Flex px={['6','7','9','12']} pt="3" pb="5">
              <Heading size="lg" fontFamily="bogart"> Hai I am Asep, a Back End Developer in Sineashub for their streaming website. </Heading>
            </Flex>
            <Flex px={['6', '7', '9', "12"]} direction="column" >
              <Text sx={textAbout} fontFamily="montserrat"> I am graduated from SMK TI Pembangunan Cimahi in 2021, after graduated I learn many things about
                programing language for web development like PHP, Javascript, Python, etc. </Text>
            </Flex>
          </Flex>
        </Flex>
      </Box>
      <Box px="9" py="32" mt="10" id="pendidikan">
        <Heading fontFamily="Bogart" as='h2'>Education</Heading>
        <Flex>
          
        </Flex>
      </Box>
      <Box id='projek' px="9" py="32" mt="10">
        <Heading fontFamily='Bogart' as='h2'>Project</Heading>
      </Box>
    </>
  )
}
